# Generated by Django 2.2.7 on 2019-11-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='agendapp.Login'),
        ),
    ]
